import '@/assets/style/reset.css';
import RoyHeader from '@/components/Header';
import RyoMenu from '@/components/SideMenu';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './index.scss';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-mode="light" className="font-ryo">
        <Providers>
          <RyoMenu />
          <main id="ryo-main">
            <RoyHeader />
            <div className="main-content">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
