#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 commit前置操作'

echo '👷‍♀️代码格式化'
# Check Prettier standards
npm run format ||
(
    echo '🤢🤮🤢🤮 格式化失败';
    false;
)

echo '👷‍♀️lint修复'
npm run lint ||
(
    echo 'lint 自动修复失败 😤🏀👋😤'
    false; 
)